# Generated by Django 6.0.7 on 2026-08-09 08:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farm_gps_accuracy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('crop', models.CharField(blank=True, max_length=100, null=True)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_zones', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('collection_method', models.CharField(choices=[('MANUAL', 'Manual Collection'), ('SENSOR', 'Sensor Collection'), ('LAB', 'Laboratory Collection')], default='MANUAL', max_length=20)),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sampling_depth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('RECEIVED', 'Received'), ('TESTING', 'Testing'), ('TESTED', 'Tested'), ('REJECTED', 'Rejected')], default='COLLECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_soil_samples', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_samples', to='farms.farm')),
                ('sampling_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soil_samples', to='soil.samplingzone')),
            ],
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test_method', models.CharField(choices=[('SOILGENIE_SENSOR', 'SoilGenie Sensor'), ('LABORATORY', 'Laboratory'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_tests', to='soil.soilsample')),
            ],
        ),
        migrations.CreateModel(
            name='SoilTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nitrogen_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phosphorus_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('potassium_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moisture_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('electrical_conductivity_ds_m', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('organic_matter_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='soil.soiltest')),
            ],
        ),
    ]
