# Generated by Django 6.0.7 on 2026-08-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('GOOD', 'Good'), ('MODERATE', 'Moderate'), ('POOR', 'Poor'), ('CRITICAL', 'Critical')], default='MODERATE', max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('ph_status', models.CharField(blank=True, max_length=20, null=True)),
                ('nitrogen_status', models.CharField(blank=True, max_length=20, null=True)),
                ('phosphorus_status', models.CharField(blank=True, max_length=20, null=True)),
                ('potassium_status', models.CharField(blank=True, max_length=20, null=True)),
                ('moisture_status', models.CharField(blank=True, max_length=20, null=True)),
                ('organic_matter_status', models.CharField(blank=True, max_length=20, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('fertilizer_recommendation', models.TextField(blank=True, null=True)),
                ('amendment_recommendation', models.TextField(blank=True, null=True)),
                ('irrigation_recommendation', models.TextField(blank=True, null=True)),
                ('crop_recommendation', models.TextField(blank=True, null=True)),
                ('generated_by', models.CharField(default='SOILGENIE_RULE_ENGINE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='soil.soiltest')),
            ],
        ),
    ]
