# Generated by Django 6.0.7 on 2026-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0002_soilanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('min_nitrogen_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_nitrogen_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_phosphorus_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_phosphorus_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_potassium_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_potassium_mg_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_moisture_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_moisture_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_organic_matter_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_ec_ds_m', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('water_requirement', models.CharField(blank=True, max_length=30, null=True)),
                ('growing_season', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
