# Generated by Django 6.0.7 on 2026-08-08 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('farm_name', models.CharField(max_length=150)),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Farm size in hectares.', max_digits=10)),
                ('primary_crop', models.CharField(blank=True, max_length=100, null=True)),
                ('farming_type', models.CharField(choices=[('SMALLHOLDER', 'Smallholder'), ('COMMERCIAL', 'Commercial'), ('COOPERATIVE', 'Cooperative')], default='SMALLHOLDER', max_length=20)),
                ('irrigation_type', models.CharField(choices=[('RAIN_FED', 'Rain-fed'), ('IRRIGATED', 'Irrigated'), ('MIXED', 'Mixed')], default='RAIN_FED', max_length=20)),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Owned'), ('LEASED', 'Leased'), ('COMMUNAL', 'Communal'), ('FAMILY', 'Family'), ('OTHER', 'Other')], default='OWNED', max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude.', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmers.farmer')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
