# Generated by Django 6.0.7 on 2026-08-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='gps_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in metres.', max_digits=8, null=True),
        ),
    ]
